apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: piguncle
data:
  redis.conf: |-
    protected-mode no
    port 6379
    timeout 0
    tcp-keepalive 300

    daemonize no
    pidfile /var/run/redis.pid

    loglevel notice

    databases 16
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    dir /app/data

    appendonly no
    requirepass 123456
